version: 0.0.11

servers:
  - name: partner
    host: https://partner.api.flow.io

operations:
  - method: GET
    path: /partners/:partner/labels
    server: partner
  - method: GET
    path: /partners/:partner/labels/:id
    server: partner
  - method: POST
    path: /partners/:partner/labels
    server: partner
