version: 0.0.18

servers:
  - name: partner
    host: https://partner.api.flow.io

operations:
  - method: GET
    path: /partners/:partner/labels
    server: partner
  - method: GET
    path: /partners/:partner/labels/:id
    server: partner
  - method: POST
    path: /partners/:partner/labels
    server: partner
  - method: GET
    path: /partners/:partner/order-identifiers/:number
    server: partner
  - method: PUT
    path: /partners/:partner/order-identifiers/:number
    server: partner
  - method: DELETE
    path: /partners/:partner/order-identifiers/:number
    server: partner
  - method: GET
    path: /partners/:partner/returns
    server: partner
  - method: GET
    path: /partners/:partner/returns/:id
    server: partner
  - method: POST
    path: /partners/:partner/returns
    server: partner
