version: 0.0.9

servers:
  - name: partner
    host: https://partner.api.flow.io

operations:
  - method: GET
    path: /partners/:partner/labels
    server: partner
  - method: GET
    path: /partners/:partner/labels/:id
    server: partner
  - method: POST
    path: /partners/:partner/labels
    server: partner
  - method: GET
    path: /internal/partners/:id
    server: partner
  - method: POST
    path: /internal/partners
    server: partner
  - method: DELETE
    path: /internal/partners/:id
    server: partner
  - method: POST
    path: /partner-authorizations
    server: partner
  - method: GET
    path: /partner-authorizations/:partner
    server: partner
  - method: GET
    path: /partners/:partner/memberships
    server: partner
  - method: GET
    path: /partners/:partner/memberships/versions
    server: partner
  - method: GET
    path: /partners/:partner/memberships/:id
    server: partner
  - method: POST
    path: /partners/:partner/memberships
    server: partner
  - method: PUT
    path: /partners/:partner/memberships/:id
    server: partner
  - method: DELETE
    path: /partners/:partner/memberships/:id
    server: partner
  - method: GET
    path: /:organization/partner-organization-authorizations
    server: partner
  - method: GET
    path: /:organization/partner-organization-authorizations/:id
    server: partner
  - method: POST
    path: /:organization/partner-organization-authorizations
    server: partner
  - method: DELETE
    path: /:organization/partner-organization-authorizations/:id
    server: partner
