version: 0.0.80

servers:
  - name: billing-internal
    host: http://localhost:7121
  - name: billing
    host: http://localhost:7121
  - name: currency-internal
    host: http://localhost:6321
  - name: experience-internal
    host: http://localhost:6251
  - name: fulfillment-internal
    host: http://localhost:6061
  - name: ratecard
    host: http://localhost:7021
  - name: screen
    host: http://localhost:7081
  - name: search-internal
    host: http://localhost:6331
  - name: user-internal
    host: http://localhost:6021

operations:
  - method: PUT
    path: /internal/accounts/:organization_id/:currency
    server: billing-internal
  - method: DELETE
    path: /internal/:organization/payments/:reference
    server: billing-internal
  - method: POST
    path: /internal/:organization/payments/:reference/close
    server: billing-internal
  - method: GET
    path: /:organization/accounts
    server: billing
  - method: GET
    path: /:organization/accounts/:currency
    server: billing
  - method: GET
    path: /:organization/accounts/:currency/statistics
    server: billing
  - method: GET
    path: /:organization/accounts/:currency/entries
    server: billing
  - method: POST
    path: /:organization/accounts/:currency/email
    server: billing
  - method: GET
    path: /:organization/payments
    server: billing
  - method: GET
    path: /:organization/payments/:reference
    server: billing
  - method: GET
    path: /:organization/payments/:payment_reference/entries
    server: billing
  - method: GET
    path: /:organization/account/transaction/summaries
    server: billing
  - method: GET
    path: /:organization/account/transaction/summaries/:id
    server: billing
  - method: GET
    path: /internal/currency/settings
    server: currency-internal
  - method: GET
    path: /internal/currency/settings/versions
    server: currency-internal
  - method: GET
    path: /internal/currency/settings/:id
    server: currency-internal
  - method: POST
    path: /internal/currency/settings
    server: currency-internal
  - method: PUT
    path: /internal/currency/settings/:id
    server: currency-internal
  - method: GET
    path: /internal/currency/spot-rates
    server: currency-internal
  - method: GET
    path: /internal/currency/spot-rates/versions
    server: currency-internal
  - method: PUT
    path: /:organization/experiences/:key/formatting/options
    server: experience-internal
  - method: GET
    path: /:organization/experiences/:key/formatting/options/:currency/:amount
    server: experience-internal
  - method: GET
    path: /:organization/experiences/:key/formatting
    server: experience-internal
  - method: GET
    path: /carriers
    server: fulfillment-internal
  - method: GET
    path: /carriers/:id
    server: fulfillment-internal
  - method: GET
    path: /carriers/versions
    server: fulfillment-internal
  - method: POST
    path: /carriers
    server: fulfillment-internal
  - method: PUT
    path: /carriers/:id
    server: fulfillment-internal
  - method: DELETE
    path: /carriers/:id
    server: fulfillment-internal
  - method: GET
    path: /services
    server: fulfillment-internal
  - method: GET
    path: /services/:id
    server: fulfillment-internal
  - method: GET
    path: /services/versions
    server: fulfillment-internal
  - method: POST
    path: /services
    server: fulfillment-internal
  - method: PUT
    path: /services/:id
    server: fulfillment-internal
  - method: DELETE
    path: /services/:id
    server: fulfillment-internal
  - method: GET
    path: /:organization/dimension-estimates/versions
    server: ratecard
  - method: GET
    path: /:organization/dimension-estimates
    server: ratecard
  - method: GET
    path: /:organization/dimension-estimates/:id
    server: ratecard
  - method: POST
    path: /:organization/dimension-estimates
    server: ratecard
  - method: DELETE
    path: /:organization/dimension-estimates/:id
    server: ratecard
  - method: GET
    path: /:organization/ratecards/versions
    server: ratecard
  - method: GET
    path: /:organization/ratecards
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:id
    server: ratecard
  - method: POST
    path: /:organization/ratecards
    server: ratecard
  - method: PUT
    path: /:organization/ratecards/:id/publish
    server: ratecard
  - method: POST
    path: /:organization/ratecard_estimates
    server: ratecard
  - method: GET
    path: /:organization/ratecard-lanes/versions
    server: ratecard
  - method: GET
    path: /:organization/ratecard-lanes
    server: ratecard
  - method: GET
    path: /:organization/ratecard-lanes/:id
    server: ratecard
  - method: POST
    path: /:organization/ratecard-lanes
    server: ratecard
  - method: PUT
    path: /:organization/ratecard-lanes/:id
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates/versions
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates/:id
    server: ratecard
  - method: POST
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates
    server: ratecard
  - method: PUT
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates/:id
    server: ratecard
  - method: PUT
    path: /screens/:key
    server: screen
  - method: GET
    path: /:organization/harmonization/countries
    server: search-internal
  - method: GET
    path: /:organization/harmonization/statistics
    server: search-internal
  - method: GET
    path: /:organization/harmonization/summaries
    server: search-internal
  - method: GET
    path: /:organization/harmonization/codes/hs10
    server: search-internal
  - method: GET
    path: /:organization/harmonization/codes/hs6
    server: search-internal
  - method: GET
    path: /:organization/customers
    server: search-internal
  - method: GET
    path: /:organization/customers/:number
    server: search-internal
  - method: GET
    path: /:organization/order-details
    server: search-internal
  - method: GET
    path: /:organization/order-details/:number
    server: search-internal
  - method: PUT
    path: /internal/users/:id/status
    server: user-internal
  - method: POST
    path: /users/tokens/redeem
    server: user-internal
  - method: POST
    path: /users/tokens
    server: user-internal
