version: 0.0.33

servers:
  - name: currency-internal
    host: http://172.17.0.1:6321
  - name: fulfillment-internal
    host: http://172.17.0.1:6061
  - name: ratecard
    host: http://172.17.0.1:7021
  - name: search-internal
    host: http://172.17.0.1:6331
  - name: user-internal
    host: http://172.17.0.1:6021

operations:
  - method: GET
    path: /internal/currency/rates
    server: currency-internal
  - method: GET
    path: /internal/currency/rates/versions
    server: currency-internal
  - method: GET
    path: /internal/currency/settings
    server: currency-internal
  - method: GET
    path: /internal/currency/settings/versions
    server: currency-internal
  - method: GET
    path: /internal/currency/settings/:id
    server: currency-internal
  - method: POST
    path: /internal/currency/settings
    server: currency-internal
  - method: PUT
    path: /internal/currency/settings/:id
    server: currency-internal
  - method: GET
    path: /carriers/versions
    server: fulfillment-internal
  - method: POST
    path: /carriers
    server: fulfillment-internal
  - method: PUT
    path: /carriers/:id
    server: fulfillment-internal
  - method: DELETE
    path: /carriers/:id
    server: fulfillment-internal
  - method: GET
    path: /services/versions
    server: fulfillment-internal
  - method: POST
    path: /services
    server: fulfillment-internal
  - method: PUT
    path: /services/:id
    server: fulfillment-internal
  - method: DELETE
    path: /services/:id
    server: fulfillment-internal
  - method: GET
    path: /:organization/ratecards/versions
    server: ratecard
  - method: GET
    path: /:organization/ratecards
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:id
    server: ratecard
  - method: POST
    path: /:organization/ratecards
    server: ratecard
  - method: PUT
    path: /:organization/ratecards/:id/publish
    server: ratecard
  - method: GET
    path: /:organization/ratecard_estimates
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/versions
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:id
    server: ratecard
  - method: POST
    path: /:organization/ratecards/:ratecard_id/lanes
    server: ratecard
  - method: PUT
    path: /:organization/ratecards/:ratecard_id/lanes/:id
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates/versions
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates/:id
    server: ratecard
  - method: POST
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates
    server: ratecard
  - method: PUT
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates/:id
    server: ratecard
  - method: GET
    path: /:organization/customers
    server: search-internal
  - method: GET
    path: /:organization/customers/:number
    server: search-internal
  - method: GET
    path: /:organization/order-details
    server: search-internal
  - method: GET
    path: /:organization/order-details/:number
    server: search-internal
  - method: PUT
    path: /internal/users/:id/status
    server: user-internal
  - method: POST
    path: /users/:id/tokens
    server: user-internal
