version: 0.0.25

servers:
  - name: partner
    host: http://172.17.0.1:7061

operations:
  - method: GET
    path: /partners/:partner/labels
    server: partner
  - method: GET
    path: /partners/:partner/labels/:id
    server: partner
  - method: POST
    path: /partners/:partner/labels
    server: partner
  - method: GET
    path: /partners/:partner/manifests/type/all
    server: partner
  - method: POST
    path: /partners/:partner/manifests/type/list
    server: partner
  - method: GET
    path: /partners/:partner/manifests
    server: partner
  - method: GET
    path: /partners/:partner/manifests/:id
    server: partner
  - method: GET
    path: /partners/:partner/organizations/:organization/order-identifiers
    server: partner
  - method: GET
    path: /partners/:partner/organizations/:organization/order-identifiers/:number
    server: partner
  - method: POST
    path: /partners/:partner/organizations/:organization/order-identifiers
    server: partner
  - method: PUT
    path: /partners/:partner/organizations/:organization/order-identifiers/:number
    server: partner
  - method: DELETE
    path: /partners/:partner/organizations/:organization/order-identifiers/:number
    server: partner
  - method: GET
    path: /partners/:partner/returns
    server: partner
  - method: GET
    path: /partners/:partner/returns/:id
    server: partner
  - method: POST
    path: /partners/:partner/returns
    server: partner
