version: 0.0.14

servers:
  - name: partner
    host: https://partner.api.flow.io

operations:
  - method: GET
    path: /partners/:partner/labels
    server: partner
  - method: GET
    path: /partners/:partner/labels/:id
    server: partner
  - method: POST
    path: /partners/:partner/labels
    server: partner
  - method: GET
    path: /partners/:partner/returns
    server: partner
  - method: GET
    path: /partners/:partner/returns/:key
    server: partner
  - method: POST
    path: /partners/:partner/returns
    server: partner
