version: 0.0.33

servers:
  - name: currency-internal
    host: https://currency.api.flow.io
  - name: experience-internal
    host: https://experience.api.flow.io
  - name: fulfillment-internal
    host: https://fulfillment.api.flow.io
  - name: invoice
    host: https://invoice.api.flow.io
  - name: ratecard
    host: https://ratecard.api.flow.io
  - name: screen
    host: https://screen.api.flow.io
  - name: search-internal
    host: https://search.api.flow.io
  - name: user-internal
    host: https://user.api.flow.io

operations:
  - method: GET
    path: /internal/currency/rates
    server: currency-internal
  - method: GET
    path: /internal/currency/rates/versions
    server: currency-internal
  - method: GET
    path: /internal/currency/settings
    server: currency-internal
  - method: GET
    path: /internal/currency/settings/versions
    server: currency-internal
  - method: GET
    path: /internal/currency/settings/:id
    server: currency-internal
  - method: POST
    path: /internal/currency/settings
    server: currency-internal
  - method: PUT
    path: /internal/currency/settings/:id
    server: currency-internal
  - method: PUT
    path: /:organization/experiences/:key/formatting/options
    server: experience-internal
  - method: GET
    path: /:organization/experiences/:key/formatting/options/:currency/:amount
    server: experience-internal
  - method: GET
    path: /:organization/experiences/:key/formatting
    server: experience-internal
  - method: GET
    path: /carriers
    server: fulfillment-internal
  - method: GET
    path: /carriers/:id
    server: fulfillment-internal
  - method: GET
    path: /carriers/versions
    server: fulfillment-internal
  - method: POST
    path: /carriers
    server: fulfillment-internal
  - method: PUT
    path: /carriers/:id
    server: fulfillment-internal
  - method: DELETE
    path: /carriers/:id
    server: fulfillment-internal
  - method: GET
    path: /services
    server: fulfillment-internal
  - method: GET
    path: /services/:id
    server: fulfillment-internal
  - method: GET
    path: /services/versions
    server: fulfillment-internal
  - method: POST
    path: /services
    server: fulfillment-internal
  - method: PUT
    path: /services/:id
    server: fulfillment-internal
  - method: DELETE
    path: /services/:id
    server: fulfillment-internal
  - method: GET
    path: /:organization/invoices
    server: invoice
  - method: POST
    path: /:organization/invoices/:number/email
    server: invoice
  - method: GET
    path: /:organization/invoices/master
    server: invoice
  - method: PUT
    path: /:organization/invoices/master
    server: invoice
  - method: GET
    path: /:organization/invoices/:number
    server: invoice
  - method: DELETE
    path: /:organization/invoices/:number
    server: invoice
  - method: GET
    path: /:organization/dimension-estimates/versions
    server: ratecard
  - method: GET
    path: /:organization/dimension-estimates
    server: ratecard
  - method: GET
    path: /:organization/dimension-estimates/:id
    server: ratecard
  - method: POST
    path: /:organization/dimension-estimates
    server: ratecard
  - method: DELETE
    path: /:organization/dimension-estimates/:id
    server: ratecard
  - method: GET
    path: /:organization/ratecards/versions
    server: ratecard
  - method: GET
    path: /:organization/ratecards
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:id
    server: ratecard
  - method: POST
    path: /:organization/ratecards
    server: ratecard
  - method: PUT
    path: /:organization/ratecards/:id/publish
    server: ratecard
  - method: POST
    path: /:organization/ratecard_estimates
    server: ratecard
  - method: GET
    path: /:organization/ratecard-lanes/versions
    server: ratecard
  - method: GET
    path: /:organization/ratecard-lanes
    server: ratecard
  - method: GET
    path: /:organization/ratecard-lanes/:id
    server: ratecard
  - method: POST
    path: /:organization/ratecard-lanes
    server: ratecard
  - method: PUT
    path: /:organization/ratecard-lanes/:id
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates/versions
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates/:id
    server: ratecard
  - method: POST
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates
    server: ratecard
  - method: PUT
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates/:id
    server: ratecard
  - method: PUT
    path: /screens/:key
    server: screen
  - method: GET
    path: /:organization/customers
    server: search-internal
  - method: GET
    path: /:organization/customers/:number
    server: search-internal
  - method: GET
    path: /:organization/order-details
    server: search-internal
  - method: GET
    path: /:organization/order-details/:number
    server: search-internal
  - method: PUT
    path: /internal/users/:id/status
    server: user-internal
  - method: POST
    path: /users/tokens/redeem
    server: user-internal
  - method: POST
    path: /users/tokens
    server: user-internal
