version: 0.0.20

servers:
  - name: currency-internal
    host: https://currency.api.flow.io
  - name: fulfillment-internal
    host: https://fulfillment.api.flow.io
  - name: ratecard
    host: https://ratecard.api.flow.io

operations:
  - method: GET
    path: /internal/currency/rates
    server: currency-internal
  - method: GET
    path: /internal/currency/rates/versions
    server: currency-internal
  - method: GET
    path: /internal/currency/settings
    server: currency-internal
  - method: GET
    path: /internal/currency/settings/versions
    server: currency-internal
  - method: GET
    path: /internal/currency/settings/:id
    server: currency-internal
  - method: POST
    path: /internal/currency/settings
    server: currency-internal
  - method: PUT
    path: /internal/currency/settings/:id
    server: currency-internal
  - method: GET
    path: /carriers/versions
    server: fulfillment-internal
  - method: POST
    path: /carriers
    server: fulfillment-internal
  - method: PUT
    path: /carriers/:id
    server: fulfillment-internal
  - method: DELETE
    path: /carriers/:id
    server: fulfillment-internal
  - method: GET
    path: /services/versions
    server: fulfillment-internal
  - method: POST
    path: /services
    server: fulfillment-internal
  - method: PUT
    path: /services/:id
    server: fulfillment-internal
  - method: DELETE
    path: /services/:id
    server: fulfillment-internal
  - method: GET
    path: /:organization/ratecards/versions
    server: ratecard
  - method: GET
    path: /:organization/ratecards
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:id
    server: ratecard
  - method: POST
    path: /:organization/ratecards
    server: ratecard
  - method: PUT
    path: /:organization/ratecards/:id/publish
    server: ratecard
  - method: GET
    path: /:organization/ratecard_estimates
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/versions
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:id
    server: ratecard
  - method: POST
    path: /:organization/ratecards/:ratecard_id/lanes
    server: ratecard
  - method: PUT
    path: /:organization/ratecards/:ratecard_id/lanes/:id
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates/versions
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates
    server: ratecard
  - method: GET
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates/:id
    server: ratecard
  - method: POST
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates
    server: ratecard
  - method: PUT
    path: /:organization/ratecards/:ratecard_id/lanes/:lane_id/rates/:id
    server: ratecard
