version: 0.0.5

servers:
  - name: partner
    host: https://partner.api.flow.io

operations:
  - method: GET
    path: /partners/:partner/labels
    server: partner
  - method: GET
    path: /partners/:partner/labels/:id
    server: partner
  - method: POST
    path: /partners/:partner/labels
    server: partner
  - method: GET
    path: /internal/partners/:id
    server: partner
  - method: POST
    path: /internal/partners
    server: partner
  - method: DELETE
    path: /internal/partners/:id
    server: partner
  - method: GET
    path: /internal/partner-authorizations/:id
    server: partner
  - method: POST
    path: /internal/partner-authorizations
    server: partner
  - method: DELETE
    path: /internal/partner-authorizations/:id
    server: partner
